# Define user variables before includes so that
# other files can substitute our variables.
CFLAGS            += -g
PROJ_NAME          =  lab1

STM32DISCOVERY_LIB=../
include $(STM32DISCOVERY_LIB)/STM32-asm-openocd.rules
# vim: set ft=make:
